import { pgTable, serial, text, boolean, integer, timestamp, bigint, json } from 'drizzle-orm/pg-core';

// Users table
export const users = pgTable('users', {
  id: serial('id').primaryKey(),

  firstName: text('first_name').notNull(),
  lastName: text('last_name').notNull(),

  email: text('email').notNull().unique(),
  password: text('password').notNull(),

  createdAt: timestamp('created_at').defaultNow(),
});

// Todos table
export const todos = pgTable('todos', {
  id: serial('id').primaryKey(),
  text: text('text').notNull(),
  completed: boolean('completed').default(false).notNull(),
  // This links the todo to a specific user
  userId: integer('user_id').references(() => users.id).notNull(),
  createdAt: timestamp('created_at').defaultNow(),
});

export const chats = pgTable('chats', {
  // 'serial' creates the 1, 2, 3 sequence seen in your screenshot
  id: serial('id').primaryKey(),

  userId: integer('user_id')
    .references(() => users.id)
    .notNull(),

  createdAt: timestamp('created_at').defaultNow().notNull(),
});

export const chatMessages = pgTable('chat_messages', {
  id: serial('id').primaryKey(),

  // Change this back to integer to match the new chats.id
  chatId: integer('chat_id')
    .references(() => chats.id)
    .notNull(),

  role: text('role').notNull(), 
  text: text('text'),
  // optional JSON list of suggestions generated by the assistant
  suggestions: json('suggestions'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
});